# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(955, 672)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.execute_button = QtWidgets.QPushButton(Form)
        self.execute_button.setObjectName("execute_button")
        self.horizontalLayout_3.addWidget(self.execute_button)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.documentation = QtWidgets.QTextEdit(Form)
        self.documentation.setObjectName("documentation")
        self.gridLayout_3.addWidget(self.documentation, 5, 1, 1, 1)
        self.function_name = QtWidgets.QComboBox(Form)
        self.function_name.setEditable(True)
        self.function_name.setObjectName("function_name")
        self.gridLayout_3.addWidget(self.function_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setToolTip("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fromfile_checkbox = QtWidgets.QCheckBox(Form)
        self.fromfile_checkbox.setObjectName("fromfile_checkbox")
        self.horizontalLayout_5.addWidget(self.fromfile_checkbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.save_file_button = QtWidgets.QPushButton(Form)
        self.save_file_button.setObjectName("save_file_button")
        self.horizontalLayout_5.addWidget(self.save_file_button)
        self.load_file_button = QtWidgets.QPushButton(Form)
        self.load_file_button.setObjectName("load_file_button")
        self.horizontalLayout_5.addWidget(self.load_file_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.macrofile = QtWidgets.QLineEdit(Form)
        self.macrofile.setObjectName("macrofile")
        self.horizontalLayout_6.addWidget(self.macrofile)
        self.filebrowse_button = QtWidgets.QToolButton(Form)
        self.filebrowse_button.setObjectName("filebrowse_button")
        self.horizontalLayout_6.addWidget(self.filebrowse_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout1 = QtWidgets.QVBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout1.addWidget(self.textBrowser)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.import_button = QtWidgets.QPushButton(Form)
        self.import_button.setObjectName("import_button")
        self.horizontalLayout_4.addWidget(self.import_button)
        self.export_button = QtWidgets.QPushButton(Form)
        self.export_button.setObjectName("export_button")
        self.horizontalLayout_4.addWidget(self.export_button)
        self.horizontalLayout1.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.horizontalLayout1)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 1)
        from calibre.gui2.tweak_book.editor.text import TextEdit
        self.program = TextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.program.sizePolicy().hasHeightForWidth())
        self.program.setSizePolicy(sizePolicy)
        self.program.setMinimumSize(QtCore.QSize(400, 0))
        self.program.setDocumentTitle("")
        self.program.setTabStopWidth(30)
        self.program.setObjectName("program")
        self.gridLayout.addWidget(self.program, 2, 0, 1, 1)
        self.label_4.setBuddy(self.program)
        self.label_2.setBuddy(self.function_name)
        self.label_3.setBuddy(self.macrofile)
        self.label_41.setBuddy(self.documentation)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        Form.setWindowTitle(_("Form"))
        self.label_4.setText(_("&Program Code: (be sure to follow python indenting rules)"))
        self.execute_button.setText(_("&Execute"))
        self.function_name.setToolTip(_("Select or enter the name of the macro to create."))
        self.label_2.setText(_("&Macro:"))
        self.label_3.setText(_("Macro &file:"))
        self.fromfile_checkbox.setToolTip(_("If checked, macro\'s program code will be loaded from specified file everytime before execute. So, you can edit program code using external editor and execute it directly. Othewise, program code is saved inside calibre\'s preference file."))
        self.fromfile_checkbox.setText(_("Execute from a file"))
        self.save_file_button.setToolTip(_("Save current program code to a file"))
        self.save_file_button.setText(_("&Save to file"))
        self.load_file_button.setToolTip(_("Load macro from a file for current macro"))
        self.load_file_button.setText(_("&Load from file"))
        self.delete_button.setToolTip(_("Delete current macro."))
        self.delete_button.setText(_("&Delete macro"))
        self.save_button.setToolTip(_("Save current macro."))
        self.save_button.setText(_("&Save macro"))
        self.label_41.setText(_("&Documentation:"))
        self.macrofile.setToolTip(_("File path to program code saved to, loaded from, and executed from if \"Execute from a file\" is checked."))
        self.filebrowse_button.setText(_("..."))
        self.import_button.setToolTip(_("Import previously exported macros."))
        self.import_button.setText(_("&Import previously exported macros"))
        self.export_button.setToolTip(_("Export all macros\'s program code and settings into single json file. Useful for moving macros to another computer or making a backup."))
        self.export_button.setText(_("&Export all macros"))

